import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

/**
 * Configuração flat do ESLint 9.
 *
 * O projeto tinha `eslint` e os plugins nas devDependencies mas NENHUM arquivo
 * de configuração, então `npm run lint` morria com
 * "ESLint couldn't find an eslint.config.(js|mjs|cjs) file" (exit 2) e não havia
 * análise estática nenhuma — nem local, nem em CI.
 */
export default tseslint.config(
  { ignores: ["dist", "node_modules", "read-create-play-main", "supabase/functions"] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: { ...globals.browser, ...globals.node },
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],

      // Regras de qualidade que a auditoria apontou como dívida acumulada
      // (112 `: any`, 47 `as any`, 12 `console.log` em src).
      // Começam como warning para não travar o build; o objetivo é zerar e
      // depois promovê-las a error.
      "@typescript-eslint/no-explicit-any": "warn",
      "no-console": ["warn", { allow: ["warn", "error"] }],
      "no-debugger": "error",
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      eqeqeq: ["warn", "smart"],

      // Warnings por decisão: são violações cosméticas ou vivem em código
      // gerado (shadcn/ui, arquivos do Lovable) que não vale a pena reescrever.
      // Ficam visíveis no relatório sem travar o CI.
      "no-useless-escape": "warn",
      "@typescript-eslint/no-empty-object-type": "warn",
      "@typescript-eslint/no-require-imports": "warn",
    },
  }
,
  {
    // Arquivos gerados automaticamente pelo Lovable (banner
    // "This file is automatically generated. Do not edit it directly.").
    // Qualquer reescrita seria desfeita na próxima geração.
    files: ["src/integrations/supabase/**"],
    rules: { "prefer-const": "warn" },
  }
);